# -*- coding: utf-8 -*-
"""Duplicate Value

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lObDMUgazb7feCoC-aivxh-fBsErwNkz
"""

import numpy as np
import pandas as pd

#the first step is to load the dataset and find out the shape of that dataset.
a1=pd.read_csv('weatherHistory.csv')
a1.shape

#here it check the duplicate value in the dataset.
dupes=a1.duplicated(keep='first')# here keep='first' means it considers first value as unique and rest of the same values as duplicate.
sum(dupes)#this gives the total number of duplicates.

#It removes the duplicates values
remove_dups=a1.drop_duplicates()

remove_dups.shape# this gives the new shape of the dataset after removing duplicate value.